/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) intfunc_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[4] = {0, 1, 0, 0};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s4[18] = {6, 6, 0, 0, 1, 3, 5, 7, 9, 0, 3, 5, 2, 3, 3, 5, 4, 5};
static const casadi_int casadi_s5[9] = {0, 6, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s6[3] = {6, 0, 0};
static const casadi_int casadi_s7[3] = {0, 0, 0};

/* dae:(t[0],x[6],z[0],p[9],u)->(ode[6],alg[0],quad[0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[4]? arg[4][0] : 0;
  if (res[0]!=0) res[0][1]=a0;
  a1=arg[1]? arg[1][3] : 0;
  if (res[0]!=0) res[0][2]=a1;
  a2=5.0000000000000000e-01;
  a3=(a2*a0);
  a4=arg[3]? arg[3][1] : 0;
  a5=casadi_sq(a4);
  a3=(a3*a5);
  a5=arg[3]? arg[3][2] : 0;
  a3=(a3*a5);
  a6=arg[3]? arg[3][4] : 0;
  a7=casadi_sq(a6);
  a3=(a3*a7);
  a7=arg[1]? arg[1][2] : 0;
  a8=2.;
  a9=arg[1]? arg[1][4] : 0;
  a10=(a8*a9);
  a10=(a7+a10);
  a10=cos(a10);
  a3=(a3*a10);
  a10=arg[3]? arg[3][8] : 0;
  a11=(a10*a0);
  a12=arg[3]? arg[3][0] : 0;
  a11=(a11*a12);
  a13=arg[3]? arg[3][3] : 0;
  a11=(a11*a13);
  a14=cos(a7);
  a11=(a11*a14);
  a14=(a10*a0);
  a14=(a14*a5);
  a14=(a14*a6);
  a15=cos(a7);
  a14=(a14*a15);
  a11=(a11+a14);
  a14=9.8100000000000005e+00;
  a15=(a14*a10);
  a15=(a15*a12);
  a15=(a15*a13);
  a16=sin(a7);
  a15=(a15*a16);
  a11=(a11+a15);
  a15=(a14*a10);
  a15=(a15*a5);
  a15=(a15*a6);
  a16=sin(a7);
  a15=(a15*a16);
  a11=(a11+a15);
  a15=(a0*a12);
  a16=casadi_sq(a4);
  a15=(a15*a16);
  a15=(a15*a13);
  a15=(a15*a6);
  a16=cos(a7);
  a15=(a15*a16);
  a11=(a11+a15);
  a3=(a3-a11);
  a11=(a2*a0);
  a15=casadi_sq(a4);
  a11=(a11*a15);
  a11=(a11*a5);
  a15=casadi_sq(a6);
  a11=(a11*a15);
  a15=cos(a7);
  a11=(a11*a15);
  a3=(a3-a11);
  a11=arg[3]? arg[3][5] : 0;
  a15=arg[3]? arg[3][7] : 0;
  a16=(a15*a10);
  a17=casadi_sq(a4);
  a17=(a15*a17);
  a17=(a17*a6);
  a16=(a16+a17);
  a17=casadi_sq(a12);
  a17=(a10*a17);
  a17=(a17*a13);
  a16=(a16+a17);
  a17=casadi_sq(a5);
  a17=(a10*a17);
  a17=(a17*a6);
  a16=(a16+a17);
  a17=casadi_sq(a12);
  a18=casadi_sq(a4);
  a17=(a17*a18);
  a17=(a17*a13);
  a17=(a17*a6);
  a16=(a16+a17);
  a17=casadi_sq(a4);
  a18=casadi_sq(a5);
  a17=(a17*a18);
  a18=casadi_sq(a6);
  a17=(a17*a18);
  a18=sin(a9);
  a18=casadi_sq(a18);
  a17=(a17*a18);
  a16=(a16+a17);
  a11=(a11*a16);
  a11=(a11*a1);
  a3=(a3-a11);
  a11=(a14*a12);
  a1=casadi_sq(a4);
  a11=(a11*a1);
  a11=(a11*a13);
  a11=(a11*a6);
  a1=sin(a7);
  a11=(a11*a1);
  a3=(a3-a11);
  a11=4.9050000000000002e+00;
  a1=casadi_sq(a4);
  a1=(a11*a1);
  a1=(a1*a5);
  a16=casadi_sq(a6);
  a1=(a1*a16);
  a16=(a8*a9);
  a16=(a7+a16);
  a16=sin(a16);
  a1=(a1*a16);
  a3=(a3+a1);
  a1=casadi_sq(a4);
  a1=(a11*a1);
  a1=(a1*a5);
  a16=casadi_sq(a6);
  a1=(a1*a16);
  a16=sin(a7);
  a1=(a1*a16);
  a3=(a3-a1);
  a1=(a15*a10);
  a16=casadi_sq(a4);
  a16=(a15*a16);
  a16=(a16*a6);
  a1=(a1+a16);
  a16=casadi_sq(a12);
  a16=(a10*a16);
  a16=(a16*a13);
  a1=(a1+a16);
  a16=casadi_sq(a5);
  a16=(a10*a16);
  a16=(a16*a6);
  a1=(a1+a16);
  a16=casadi_sq(a12);
  a17=casadi_sq(a4);
  a16=(a16*a17);
  a16=(a16*a13);
  a16=(a16*a6);
  a1=(a1+a16);
  a16=casadi_sq(a4);
  a17=casadi_sq(a5);
  a16=(a16*a17);
  a17=casadi_sq(a6);
  a16=(a16*a17);
  a17=sin(a9);
  a17=casadi_sq(a17);
  a16=(a16*a17);
  a1=(a1+a16);
  a3=(a3/a1);
  if (res[0]!=0) res[0][3]=a3;
  a3=arg[1]? arg[1][5] : 0;
  if (res[0]!=0) res[0][4]=a3;
  a1=(a10*a0);
  a1=(a1*a12);
  a1=(a1*a13);
  a16=cos(a7);
  a1=(a1*a16);
  a16=(a15*a0);
  a16=(a16*a4);
  a16=(a16*a6);
  a17=(a7+a9);
  a17=cos(a17);
  a16=(a16*a17);
  a17=(a14*a15);
  a17=(a17*a4);
  a17=(a17*a6);
  a18=(a7+a9);
  a18=sin(a18);
  a17=(a17*a18);
  a16=(a16+a17);
  a1=(a1-a16);
  a16=(a10*a0);
  a16=(a16*a5);
  a16=(a16*a6);
  a17=cos(a7);
  a16=(a16*a17);
  a1=(a1+a16);
  a16=(a14*a10);
  a16=(a16*a12);
  a16=(a16*a13);
  a17=sin(a7);
  a16=(a16*a17);
  a1=(a1+a16);
  a16=(a14*a10);
  a16=(a16*a5);
  a16=(a16*a6);
  a17=sin(a7);
  a16=(a16*a17);
  a1=(a1+a16);
  a16=casadi_sq(a12);
  a16=(a0*a16);
  a16=(a16*a4);
  a16=(a16*a13);
  a16=(a16*a6);
  a17=(a7+a9);
  a17=cos(a17);
  a16=(a16*a17);
  a1=(a1-a16);
  a16=(a0*a12);
  a17=casadi_sq(a4);
  a16=(a16*a17);
  a16=(a16*a13);
  a16=(a16*a6);
  a17=cos(a7);
  a16=(a16*a17);
  a1=(a1+a16);
  a16=(a2*a0);
  a16=(a16*a12);
  a16=(a16*a4);
  a16=(a16*a5);
  a16=(a16*a13);
  a16=(a16*a6);
  a17=(a7-a9);
  a17=cos(a17);
  a16=(a16*a17);
  a1=(a1+a16);
  a16=(a2*a0);
  a16=(a16*a12);
  a16=(a16*a4);
  a16=(a16*a5);
  a16=(a16*a13);
  a16=(a16*a6);
  a17=(a7+a9);
  a17=cos(a17);
  a16=(a16*a17);
  a1=(a1+a16);
  a16=(a2*a0);
  a17=casadi_sq(a4);
  a16=(a16*a17);
  a16=(a16*a5);
  a17=casadi_sq(a6);
  a16=(a16*a17);
  a17=(a8*a9);
  a17=(a7+a17);
  a17=cos(a17);
  a16=(a16*a17);
  a1=(a1-a16);
  a16=(a2*a0);
  a17=casadi_sq(a4);
  a16=(a16*a17);
  a16=(a16*a5);
  a17=casadi_sq(a6);
  a16=(a16*a17);
  a17=cos(a7);
  a16=(a16*a17);
  a1=(a1+a16);
  a16=(a2*a0);
  a16=(a16*a4);
  a17=casadi_sq(a5);
  a16=(a16*a17);
  a17=casadi_sq(a6);
  a16=(a16*a17);
  a17=(a7-a9);
  a17=cos(a17);
  a16=(a16*a17);
  a1=(a1+a16);
  a2=(a2*a0);
  a2=(a2*a4);
  a0=casadi_sq(a5);
  a2=(a2*a0);
  a0=casadi_sq(a6);
  a2=(a2*a0);
  a0=(a7+a9);
  a0=cos(a0);
  a2=(a2*a0);
  a1=(a1-a2);
  a2=arg[3]? arg[3][6] : 0;
  a0=(a15*a10);
  a16=casadi_sq(a4);
  a16=(a15*a16);
  a16=(a16*a6);
  a0=(a0+a16);
  a16=casadi_sq(a12);
  a16=(a10*a16);
  a16=(a16*a13);
  a0=(a0+a16);
  a16=casadi_sq(a5);
  a16=(a10*a16);
  a16=(a16*a6);
  a0=(a0+a16);
  a16=casadi_sq(a12);
  a17=casadi_sq(a4);
  a16=(a16*a17);
  a16=(a16*a13);
  a16=(a16*a6);
  a0=(a0+a16);
  a16=casadi_sq(a4);
  a17=casadi_sq(a5);
  a16=(a16*a17);
  a17=casadi_sq(a6);
  a16=(a16*a17);
  a17=sin(a9);
  a17=casadi_sq(a17);
  a16=(a16*a17);
  a0=(a0+a16);
  a2=(a2*a0);
  a2=(a2*a3);
  a1=(a1-a2);
  a2=casadi_sq(a12);
  a2=(a14*a2);
  a2=(a2*a4);
  a2=(a2*a13);
  a2=(a2*a6);
  a3=(a7+a9);
  a3=sin(a3);
  a2=(a2*a3);
  a1=(a1-a2);
  a14=(a14*a12);
  a2=casadi_sq(a4);
  a14=(a14*a2);
  a14=(a14*a13);
  a14=(a14*a6);
  a2=sin(a7);
  a14=(a14*a2);
  a1=(a1+a14);
  a14=(a11*a12);
  a14=(a14*a4);
  a14=(a14*a5);
  a14=(a14*a13);
  a14=(a14*a6);
  a2=(a7-a9);
  a2=sin(a2);
  a14=(a14*a2);
  a1=(a1+a14);
  a14=(a11*a12);
  a14=(a14*a4);
  a14=(a14*a5);
  a14=(a14*a13);
  a14=(a14*a6);
  a2=(a7+a9);
  a2=sin(a2);
  a14=(a14*a2);
  a1=(a1+a14);
  a14=casadi_sq(a4);
  a14=(a11*a14);
  a14=(a14*a5);
  a2=casadi_sq(a6);
  a14=(a14*a2);
  a8=(a8*a9);
  a8=(a7+a8);
  a8=sin(a8);
  a14=(a14*a8);
  a1=(a1-a14);
  a14=casadi_sq(a4);
  a14=(a11*a14);
  a14=(a14*a5);
  a8=casadi_sq(a6);
  a14=(a14*a8);
  a8=sin(a7);
  a14=(a14*a8);
  a1=(a1+a14);
  a14=(a11*a4);
  a8=casadi_sq(a5);
  a14=(a14*a8);
  a8=casadi_sq(a6);
  a14=(a14*a8);
  a8=(a7-a9);
  a8=sin(a8);
  a14=(a14*a8);
  a1=(a1+a14);
  a11=(a11*a4);
  a14=casadi_sq(a5);
  a11=(a11*a14);
  a14=casadi_sq(a6);
  a11=(a11*a14);
  a7=(a7+a9);
  a7=sin(a7);
  a11=(a11*a7);
  a1=(a1-a11);
  a11=(a15*a10);
  a7=casadi_sq(a4);
  a15=(a15*a7);
  a15=(a15*a6);
  a11=(a11+a15);
  a15=casadi_sq(a12);
  a15=(a10*a15);
  a15=(a15*a13);
  a11=(a11+a15);
  a15=casadi_sq(a5);
  a10=(a10*a15);
  a10=(a10*a6);
  a11=(a11+a10);
  a12=casadi_sq(a12);
  a10=casadi_sq(a4);
  a12=(a12*a10);
  a12=(a12*a13);
  a12=(a12*a6);
  a11=(a11+a12);
  a4=casadi_sq(a4);
  a5=casadi_sq(a5);
  a4=(a4*a5);
  a6=casadi_sq(a6);
  a4=(a4*a6);
  a9=sin(a9);
  a9=casadi_sq(a9);
  a4=(a4*a9);
  a11=(a11+a4);
  a1=(a1/a11);
  if (res[0]!=0) res[0][5]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int dae(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int dae_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int dae_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dae_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int dae_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dae_release(int mem) {
}

CASADI_SYMBOL_EXPORT void dae_incref(void) {
}

CASADI_SYMBOL_EXPORT void dae_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int dae_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int dae_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real dae_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dae_name_in(casadi_int i) {
  switch (i) {
    case 0: return "t";
    case 1: return "x";
    case 2: return "z";
    case 3: return "p";
    case 4: return "u";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dae_name_out(casadi_int i) {
  switch (i) {
    case 0: return "ode";
    case 1: return "alg";
    case 2: return "quad";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dae_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dae_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int dae_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* daeF:(t[0],x[6],z[0],p[9],u)->(ode[6],alg[0]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[4]? arg[4][0] : 0;
  if (res[0]!=0) res[0][1]=a0;
  a1=arg[1]? arg[1][3] : 0;
  if (res[0]!=0) res[0][2]=a1;
  a2=5.0000000000000000e-01;
  a3=(a2*a0);
  a4=arg[3]? arg[3][1] : 0;
  a5=casadi_sq(a4);
  a3=(a3*a5);
  a5=arg[3]? arg[3][2] : 0;
  a3=(a3*a5);
  a6=arg[3]? arg[3][4] : 0;
  a7=casadi_sq(a6);
  a3=(a3*a7);
  a7=arg[1]? arg[1][2] : 0;
  a8=2.;
  a9=arg[1]? arg[1][4] : 0;
  a10=(a8*a9);
  a10=(a7+a10);
  a10=cos(a10);
  a3=(a3*a10);
  a10=arg[3]? arg[3][8] : 0;
  a11=(a10*a0);
  a12=arg[3]? arg[3][0] : 0;
  a11=(a11*a12);
  a13=arg[3]? arg[3][3] : 0;
  a11=(a11*a13);
  a14=cos(a7);
  a11=(a11*a14);
  a14=(a10*a0);
  a14=(a14*a5);
  a14=(a14*a6);
  a15=cos(a7);
  a14=(a14*a15);
  a11=(a11+a14);
  a14=9.8100000000000005e+00;
  a15=(a14*a10);
  a15=(a15*a12);
  a15=(a15*a13);
  a16=sin(a7);
  a15=(a15*a16);
  a11=(a11+a15);
  a15=(a14*a10);
  a15=(a15*a5);
  a15=(a15*a6);
  a16=sin(a7);
  a15=(a15*a16);
  a11=(a11+a15);
  a15=(a0*a12);
  a16=casadi_sq(a4);
  a15=(a15*a16);
  a15=(a15*a13);
  a15=(a15*a6);
  a16=cos(a7);
  a15=(a15*a16);
  a11=(a11+a15);
  a3=(a3-a11);
  a11=(a2*a0);
  a15=casadi_sq(a4);
  a11=(a11*a15);
  a11=(a11*a5);
  a15=casadi_sq(a6);
  a11=(a11*a15);
  a15=cos(a7);
  a11=(a11*a15);
  a3=(a3-a11);
  a11=arg[3]? arg[3][5] : 0;
  a15=arg[3]? arg[3][7] : 0;
  a16=(a15*a10);
  a17=casadi_sq(a4);
  a17=(a15*a17);
  a17=(a17*a6);
  a16=(a16+a17);
  a17=casadi_sq(a12);
  a17=(a10*a17);
  a17=(a17*a13);
  a16=(a16+a17);
  a17=casadi_sq(a5);
  a17=(a10*a17);
  a17=(a17*a6);
  a16=(a16+a17);
  a17=casadi_sq(a12);
  a18=casadi_sq(a4);
  a17=(a17*a18);
  a17=(a17*a13);
  a17=(a17*a6);
  a16=(a16+a17);
  a17=casadi_sq(a4);
  a18=casadi_sq(a5);
  a17=(a17*a18);
  a18=casadi_sq(a6);
  a17=(a17*a18);
  a18=sin(a9);
  a18=casadi_sq(a18);
  a17=(a17*a18);
  a16=(a16+a17);
  a11=(a11*a16);
  a11=(a11*a1);
  a3=(a3-a11);
  a11=(a14*a12);
  a1=casadi_sq(a4);
  a11=(a11*a1);
  a11=(a11*a13);
  a11=(a11*a6);
  a1=sin(a7);
  a11=(a11*a1);
  a3=(a3-a11);
  a11=4.9050000000000002e+00;
  a1=casadi_sq(a4);
  a1=(a11*a1);
  a1=(a1*a5);
  a16=casadi_sq(a6);
  a1=(a1*a16);
  a16=(a8*a9);
  a16=(a7+a16);
  a16=sin(a16);
  a1=(a1*a16);
  a3=(a3+a1);
  a1=casadi_sq(a4);
  a1=(a11*a1);
  a1=(a1*a5);
  a16=casadi_sq(a6);
  a1=(a1*a16);
  a16=sin(a7);
  a1=(a1*a16);
  a3=(a3-a1);
  a1=(a15*a10);
  a16=casadi_sq(a4);
  a16=(a15*a16);
  a16=(a16*a6);
  a1=(a1+a16);
  a16=casadi_sq(a12);
  a16=(a10*a16);
  a16=(a16*a13);
  a1=(a1+a16);
  a16=casadi_sq(a5);
  a16=(a10*a16);
  a16=(a16*a6);
  a1=(a1+a16);
  a16=casadi_sq(a12);
  a17=casadi_sq(a4);
  a16=(a16*a17);
  a16=(a16*a13);
  a16=(a16*a6);
  a1=(a1+a16);
  a16=casadi_sq(a4);
  a17=casadi_sq(a5);
  a16=(a16*a17);
  a17=casadi_sq(a6);
  a16=(a16*a17);
  a17=sin(a9);
  a17=casadi_sq(a17);
  a16=(a16*a17);
  a1=(a1+a16);
  a3=(a3/a1);
  if (res[0]!=0) res[0][3]=a3;
  a3=arg[1]? arg[1][5] : 0;
  if (res[0]!=0) res[0][4]=a3;
  a1=(a10*a0);
  a1=(a1*a12);
  a1=(a1*a13);
  a16=cos(a7);
  a1=(a1*a16);
  a16=(a15*a0);
  a16=(a16*a4);
  a16=(a16*a6);
  a17=(a7+a9);
  a17=cos(a17);
  a16=(a16*a17);
  a17=(a14*a15);
  a17=(a17*a4);
  a17=(a17*a6);
  a18=(a7+a9);
  a18=sin(a18);
  a17=(a17*a18);
  a16=(a16+a17);
  a1=(a1-a16);
  a16=(a10*a0);
  a16=(a16*a5);
  a16=(a16*a6);
  a17=cos(a7);
  a16=(a16*a17);
  a1=(a1+a16);
  a16=(a14*a10);
  a16=(a16*a12);
  a16=(a16*a13);
  a17=sin(a7);
  a16=(a16*a17);
  a1=(a1+a16);
  a16=(a14*a10);
  a16=(a16*a5);
  a16=(a16*a6);
  a17=sin(a7);
  a16=(a16*a17);
  a1=(a1+a16);
  a16=casadi_sq(a12);
  a16=(a0*a16);
  a16=(a16*a4);
  a16=(a16*a13);
  a16=(a16*a6);
  a17=(a7+a9);
  a17=cos(a17);
  a16=(a16*a17);
  a1=(a1-a16);
  a16=(a0*a12);
  a17=casadi_sq(a4);
  a16=(a16*a17);
  a16=(a16*a13);
  a16=(a16*a6);
  a17=cos(a7);
  a16=(a16*a17);
  a1=(a1+a16);
  a16=(a2*a0);
  a16=(a16*a12);
  a16=(a16*a4);
  a16=(a16*a5);
  a16=(a16*a13);
  a16=(a16*a6);
  a17=(a7-a9);
  a17=cos(a17);
  a16=(a16*a17);
  a1=(a1+a16);
  a16=(a2*a0);
  a16=(a16*a12);
  a16=(a16*a4);
  a16=(a16*a5);
  a16=(a16*a13);
  a16=(a16*a6);
  a17=(a7+a9);
  a17=cos(a17);
  a16=(a16*a17);
  a1=(a1+a16);
  a16=(a2*a0);
  a17=casadi_sq(a4);
  a16=(a16*a17);
  a16=(a16*a5);
  a17=casadi_sq(a6);
  a16=(a16*a17);
  a17=(a8*a9);
  a17=(a7+a17);
  a17=cos(a17);
  a16=(a16*a17);
  a1=(a1-a16);
  a16=(a2*a0);
  a17=casadi_sq(a4);
  a16=(a16*a17);
  a16=(a16*a5);
  a17=casadi_sq(a6);
  a16=(a16*a17);
  a17=cos(a7);
  a16=(a16*a17);
  a1=(a1+a16);
  a16=(a2*a0);
  a16=(a16*a4);
  a17=casadi_sq(a5);
  a16=(a16*a17);
  a17=casadi_sq(a6);
  a16=(a16*a17);
  a17=(a7-a9);
  a17=cos(a17);
  a16=(a16*a17);
  a1=(a1+a16);
  a2=(a2*a0);
  a2=(a2*a4);
  a0=casadi_sq(a5);
  a2=(a2*a0);
  a0=casadi_sq(a6);
  a2=(a2*a0);
  a0=(a7+a9);
  a0=cos(a0);
  a2=(a2*a0);
  a1=(a1-a2);
  a2=arg[3]? arg[3][6] : 0;
  a0=(a15*a10);
  a16=casadi_sq(a4);
  a16=(a15*a16);
  a16=(a16*a6);
  a0=(a0+a16);
  a16=casadi_sq(a12);
  a16=(a10*a16);
  a16=(a16*a13);
  a0=(a0+a16);
  a16=casadi_sq(a5);
  a16=(a10*a16);
  a16=(a16*a6);
  a0=(a0+a16);
  a16=casadi_sq(a12);
  a17=casadi_sq(a4);
  a16=(a16*a17);
  a16=(a16*a13);
  a16=(a16*a6);
  a0=(a0+a16);
  a16=casadi_sq(a4);
  a17=casadi_sq(a5);
  a16=(a16*a17);
  a17=casadi_sq(a6);
  a16=(a16*a17);
  a17=sin(a9);
  a17=casadi_sq(a17);
  a16=(a16*a17);
  a0=(a0+a16);
  a2=(a2*a0);
  a2=(a2*a3);
  a1=(a1-a2);
  a2=casadi_sq(a12);
  a2=(a14*a2);
  a2=(a2*a4);
  a2=(a2*a13);
  a2=(a2*a6);
  a3=(a7+a9);
  a3=sin(a3);
  a2=(a2*a3);
  a1=(a1-a2);
  a14=(a14*a12);
  a2=casadi_sq(a4);
  a14=(a14*a2);
  a14=(a14*a13);
  a14=(a14*a6);
  a2=sin(a7);
  a14=(a14*a2);
  a1=(a1+a14);
  a14=(a11*a12);
  a14=(a14*a4);
  a14=(a14*a5);
  a14=(a14*a13);
  a14=(a14*a6);
  a2=(a7-a9);
  a2=sin(a2);
  a14=(a14*a2);
  a1=(a1+a14);
  a14=(a11*a12);
  a14=(a14*a4);
  a14=(a14*a5);
  a14=(a14*a13);
  a14=(a14*a6);
  a2=(a7+a9);
  a2=sin(a2);
  a14=(a14*a2);
  a1=(a1+a14);
  a14=casadi_sq(a4);
  a14=(a11*a14);
  a14=(a14*a5);
  a2=casadi_sq(a6);
  a14=(a14*a2);
  a8=(a8*a9);
  a8=(a7+a8);
  a8=sin(a8);
  a14=(a14*a8);
  a1=(a1-a14);
  a14=casadi_sq(a4);
  a14=(a11*a14);
  a14=(a14*a5);
  a8=casadi_sq(a6);
  a14=(a14*a8);
  a8=sin(a7);
  a14=(a14*a8);
  a1=(a1+a14);
  a14=(a11*a4);
  a8=casadi_sq(a5);
  a14=(a14*a8);
  a8=casadi_sq(a6);
  a14=(a14*a8);
  a8=(a7-a9);
  a8=sin(a8);
  a14=(a14*a8);
  a1=(a1+a14);
  a11=(a11*a4);
  a14=casadi_sq(a5);
  a11=(a11*a14);
  a14=casadi_sq(a6);
  a11=(a11*a14);
  a7=(a7+a9);
  a7=sin(a7);
  a11=(a11*a7);
  a1=(a1-a11);
  a11=(a15*a10);
  a7=casadi_sq(a4);
  a15=(a15*a7);
  a15=(a15*a6);
  a11=(a11+a15);
  a15=casadi_sq(a12);
  a15=(a10*a15);
  a15=(a15*a13);
  a11=(a11+a15);
  a15=casadi_sq(a5);
  a10=(a10*a15);
  a10=(a10*a6);
  a11=(a11+a10);
  a12=casadi_sq(a12);
  a10=casadi_sq(a4);
  a12=(a12*a10);
  a12=(a12*a13);
  a12=(a12*a6);
  a11=(a11+a12);
  a4=casadi_sq(a4);
  a5=casadi_sq(a5);
  a4=(a4*a5);
  a6=casadi_sq(a6);
  a4=(a4*a6);
  a9=sin(a9);
  a9=casadi_sq(a9);
  a4=(a4*a9);
  a11=(a11+a4);
  a1=(a1/a11);
  if (res[0]!=0) res[0][5]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int daeF(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int daeF_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int daeF_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void daeF_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int daeF_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void daeF_release(int mem) {
}

CASADI_SYMBOL_EXPORT void daeF_incref(void) {
}

CASADI_SYMBOL_EXPORT void daeF_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int daeF_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int daeF_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real daeF_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* daeF_name_in(casadi_int i) {
  switch (i) {
    case 0: return "t";
    case 1: return "x";
    case 2: return "z";
    case 3: return "p";
    case 4: return "u";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* daeF_name_out(casadi_int i) {
  switch (i) {
    case 0: return "ode";
    case 1: return "alg";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* daeF_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* daeF_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int daeF_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* jacF:(t[0],x[6],z[0],p[9],u)->(jac_ode_x[6x6,9nz],jac_alg_x[0x6],jac_ode_z[6x0],jac_alg_z[]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a9;
  a0=1.;
  if (res[0]!=0) res[0][0]=a0;
  a1=5.0000000000000000e-01;
  a2=arg[4]? arg[4][0] : 0;
  a3=(a1*a2);
  a4=arg[3]? arg[3][1] : 0;
  a5=casadi_sq(a4);
  a3=(a3*a5);
  a5=arg[3]? arg[3][2] : 0;
  a3=(a3*a5);
  a6=arg[3]? arg[3][4] : 0;
  a7=casadi_sq(a6);
  a3=(a3*a7);
  a7=arg[1]? arg[1][2] : 0;
  a8=sin(a7);
  a8=(a3*a8);
  a9=(a1*a2);
  a10=casadi_sq(a4);
  a9=(a9*a10);
  a9=(a9*a5);
  a10=casadi_sq(a6);
  a9=(a9*a10);
  a10=2.;
  a11=arg[1]? arg[1][4] : 0;
  a12=(a10*a11);
  a12=(a7+a12);
  a13=sin(a12);
  a14=(a9*a13);
  a15=9.8100000000000005e+00;
  a16=arg[3]? arg[3][8] : 0;
  a17=(a15*a16);
  a18=arg[3]? arg[3][0] : 0;
  a17=(a17*a18);
  a19=arg[3]? arg[3][3] : 0;
  a17=(a17*a19);
  a20=cos(a7);
  a20=(a17*a20);
  a21=(a16*a2);
  a21=(a21*a18);
  a21=(a21*a19);
  a22=sin(a7);
  a22=(a21*a22);
  a23=(a16*a2);
  a23=(a23*a5);
  a23=(a23*a6);
  a24=sin(a7);
  a24=(a23*a24);
  a22=(a22+a24);
  a20=(a20-a22);
  a22=(a15*a16);
  a22=(a22*a5);
  a22=(a22*a6);
  a24=cos(a7);
  a24=(a22*a24);
  a20=(a20+a24);
  a24=(a2*a18);
  a25=casadi_sq(a4);
  a24=(a24*a25);
  a24=(a24*a19);
  a24=(a24*a6);
  a25=sin(a7);
  a25=(a24*a25);
  a20=(a20-a25);
  a14=(a14+a20);
  a8=(a8-a14);
  a14=(a15*a18);
  a20=casadi_sq(a4);
  a14=(a14*a20);
  a14=(a14*a19);
  a14=(a14*a6);
  a20=cos(a7);
  a20=(a14*a20);
  a8=(a8-a20);
  a20=4.9050000000000002e+00;
  a25=casadi_sq(a4);
  a25=(a20*a25);
  a25=(a25*a5);
  a26=casadi_sq(a6);
  a25=(a25*a26);
  a26=(a10*a11);
  a26=(a7+a26);
  a27=cos(a26);
  a28=(a25*a27);
  a8=(a8+a28);
  a28=casadi_sq(a4);
  a28=(a20*a28);
  a28=(a28*a5);
  a29=casadi_sq(a6);
  a28=(a28*a29);
  a29=cos(a7);
  a29=(a28*a29);
  a8=(a8-a29);
  a29=arg[3]? arg[3][7] : 0;
  a30=(a29*a16);
  a31=casadi_sq(a4);
  a31=(a29*a31);
  a31=(a31*a6);
  a30=(a30+a31);
  a31=casadi_sq(a18);
  a31=(a16*a31);
  a31=(a31*a19);
  a30=(a30+a31);
  a31=casadi_sq(a5);
  a31=(a16*a31);
  a31=(a31*a6);
  a30=(a30+a31);
  a31=casadi_sq(a18);
  a32=casadi_sq(a4);
  a31=(a31*a32);
  a31=(a31*a19);
  a31=(a31*a6);
  a30=(a30+a31);
  a31=casadi_sq(a4);
  a32=casadi_sq(a5);
  a31=(a31*a32);
  a32=casadi_sq(a6);
  a31=(a31*a32);
  a32=sin(a11);
  a33=casadi_sq(a32);
  a33=(a31*a33);
  a30=(a30+a33);
  a8=(a8/a30);
  if (res[0]!=0) res[0][1]=a8;
  a8=(a15*a16);
  a8=(a8*a18);
  a8=(a8*a19);
  a33=cos(a7);
  a33=(a8*a33);
  a34=(a16*a2);
  a34=(a34*a18);
  a34=(a34*a19);
  a35=sin(a7);
  a35=(a34*a35);
  a36=(a15*a29);
  a36=(a36*a4);
  a36=(a36*a6);
  a37=(a7+a11);
  a38=cos(a37);
  a39=(a36*a38);
  a40=(a29*a2);
  a40=(a40*a4);
  a40=(a40*a6);
  a41=(a7+a11);
  a42=sin(a41);
  a43=(a40*a42);
  a39=(a39-a43);
  a35=(a35+a39);
  a39=(a16*a2);
  a39=(a39*a5);
  a39=(a39*a6);
  a43=sin(a7);
  a43=(a39*a43);
  a35=(a35+a43);
  a33=(a33-a35);
  a35=(a15*a16);
  a35=(a35*a5);
  a35=(a35*a6);
  a43=cos(a7);
  a43=(a35*a43);
  a33=(a33+a43);
  a43=casadi_sq(a18);
  a43=(a2*a43);
  a43=(a43*a4);
  a43=(a43*a19);
  a43=(a43*a6);
  a44=(a7+a11);
  a45=sin(a44);
  a46=(a43*a45);
  a33=(a33+a46);
  a46=(a2*a18);
  a47=casadi_sq(a4);
  a46=(a46*a47);
  a46=(a46*a19);
  a46=(a46*a6);
  a47=sin(a7);
  a47=(a46*a47);
  a33=(a33-a47);
  a47=(a1*a2);
  a47=(a47*a18);
  a47=(a47*a4);
  a47=(a47*a5);
  a47=(a47*a19);
  a47=(a47*a6);
  a48=(a7-a11);
  a49=sin(a48);
  a50=(a47*a49);
  a33=(a33-a50);
  a50=(a1*a2);
  a50=(a50*a18);
  a50=(a50*a4);
  a50=(a50*a5);
  a50=(a50*a19);
  a50=(a50*a6);
  a51=(a7+a11);
  a52=sin(a51);
  a53=(a50*a52);
  a33=(a33-a53);
  a53=(a1*a2);
  a54=casadi_sq(a4);
  a53=(a53*a54);
  a53=(a53*a5);
  a54=casadi_sq(a6);
  a53=(a53*a54);
  a54=(a10*a11);
  a54=(a7+a54);
  a55=sin(a54);
  a56=(a53*a55);
  a33=(a33+a56);
  a56=(a1*a2);
  a57=casadi_sq(a4);
  a56=(a56*a57);
  a56=(a56*a5);
  a57=casadi_sq(a6);
  a56=(a56*a57);
  a57=sin(a7);
  a57=(a56*a57);
  a33=(a33-a57);
  a57=(a1*a2);
  a57=(a57*a4);
  a58=casadi_sq(a5);
  a57=(a57*a58);
  a58=casadi_sq(a6);
  a57=(a57*a58);
  a58=(a7-a11);
  a59=sin(a58);
  a60=(a57*a59);
  a33=(a33-a60);
  a1=(a1*a2);
  a1=(a1*a4);
  a2=casadi_sq(a5);
  a1=(a1*a2);
  a2=casadi_sq(a6);
  a1=(a1*a2);
  a2=(a7+a11);
  a60=sin(a2);
  a61=(a1*a60);
  a33=(a33+a61);
  a61=casadi_sq(a18);
  a61=(a15*a61);
  a61=(a61*a4);
  a61=(a61*a19);
  a61=(a61*a6);
  a62=(a7+a11);
  a63=cos(a62);
  a64=(a61*a63);
  a33=(a33-a64);
  a15=(a15*a18);
  a64=casadi_sq(a4);
  a15=(a15*a64);
  a15=(a15*a19);
  a15=(a15*a6);
  a64=cos(a7);
  a64=(a15*a64);
  a33=(a33+a64);
  a64=(a20*a18);
  a64=(a64*a4);
  a64=(a64*a5);
  a64=(a64*a19);
  a64=(a64*a6);
  a65=(a7-a11);
  a66=cos(a65);
  a67=(a64*a66);
  a33=(a33+a67);
  a67=(a20*a18);
  a67=(a67*a4);
  a67=(a67*a5);
  a67=(a67*a19);
  a67=(a67*a6);
  a68=(a7+a11);
  a69=cos(a68);
  a70=(a67*a69);
  a33=(a33+a70);
  a70=casadi_sq(a4);
  a70=(a20*a70);
  a70=(a70*a5);
  a71=casadi_sq(a6);
  a70=(a70*a71);
  a71=(a10*a11);
  a71=(a7+a71);
  a72=cos(a71);
  a73=(a70*a72);
  a33=(a33-a73);
  a73=casadi_sq(a4);
  a73=(a20*a73);
  a73=(a73*a5);
  a74=casadi_sq(a6);
  a73=(a73*a74);
  a74=cos(a7);
  a74=(a73*a74);
  a33=(a33+a74);
  a74=(a20*a4);
  a75=casadi_sq(a5);
  a74=(a74*a75);
  a75=casadi_sq(a6);
  a74=(a74*a75);
  a75=(a7-a11);
  a76=cos(a75);
  a77=(a74*a76);
  a33=(a33+a77);
  a20=(a20*a4);
  a77=casadi_sq(a5);
  a20=(a20*a77);
  a77=casadi_sq(a6);
  a20=(a20*a77);
  a77=(a7+a11);
  a78=cos(a77);
  a79=(a20*a78);
  a33=(a33-a79);
  a79=(a29*a16);
  a80=casadi_sq(a4);
  a80=(a29*a80);
  a80=(a80*a6);
  a79=(a79+a80);
  a80=casadi_sq(a18);
  a80=(a16*a80);
  a80=(a80*a19);
  a79=(a79+a80);
  a80=casadi_sq(a5);
  a80=(a16*a80);
  a80=(a80*a6);
  a79=(a79+a80);
  a80=casadi_sq(a18);
  a81=casadi_sq(a4);
  a80=(a80*a81);
  a80=(a80*a19);
  a80=(a80*a6);
  a79=(a79+a80);
  a80=casadi_sq(a4);
  a81=casadi_sq(a5);
  a80=(a80*a81);
  a81=casadi_sq(a6);
  a80=(a80*a81);
  a81=sin(a11);
  a82=casadi_sq(a81);
  a82=(a80*a82);
  a79=(a79+a82);
  a33=(a33/a79);
  if (res[0]!=0) res[0][2]=a33;
  if (res[0]!=0) res[0][3]=a0;
  a33=arg[3]? arg[3][5] : 0;
  a82=(a29*a16);
  a83=casadi_sq(a4);
  a83=(a29*a83);
  a83=(a83*a6);
  a82=(a82+a83);
  a83=casadi_sq(a18);
  a83=(a16*a83);
  a83=(a83*a19);
  a82=(a82+a83);
  a83=casadi_sq(a5);
  a83=(a16*a83);
  a83=(a83*a6);
  a82=(a82+a83);
  a83=casadi_sq(a18);
  a84=casadi_sq(a4);
  a83=(a83*a84);
  a83=(a83*a19);
  a83=(a83*a6);
  a82=(a82+a83);
  a83=casadi_sq(a4);
  a84=casadi_sq(a5);
  a83=(a83*a84);
  a84=casadi_sq(a6);
  a83=(a83*a84);
  a84=sin(a11);
  a85=casadi_sq(a84);
  a85=(a83*a85);
  a82=(a82+a85);
  a82=(a33*a82);
  a85=(a82/a30);
  a85=(-a85);
  if (res[0]!=0) res[0][4]=a85;
  a27=(a10*a27);
  a27=(a25*a27);
  a13=(a10*a13);
  a13=(a9*a13);
  a85=arg[1]? arg[1][3] : 0;
  a84=(a84+a84);
  a86=cos(a11);
  a84=(a84*a86);
  a83=(a83*a84);
  a33=(a33*a83);
  a33=(a85*a33);
  a13=(a13+a33);
  a27=(a27-a13);
  a27=(a27/a30);
  a12=cos(a12);
  a9=(a9*a12);
  a12=cos(a7);
  a21=(a21*a12);
  a12=cos(a7);
  a23=(a23*a12);
  a21=(a21+a23);
  a23=sin(a7);
  a17=(a17*a23);
  a21=(a21+a17);
  a17=sin(a7);
  a22=(a22*a17);
  a21=(a21+a22);
  a22=cos(a7);
  a24=(a24*a22);
  a21=(a21+a24);
  a9=(a9-a21);
  a21=cos(a7);
  a3=(a3*a21);
  a9=(a9-a3);
  a82=(a82*a85);
  a9=(a9-a82);
  a82=sin(a7);
  a14=(a14*a82);
  a9=(a9-a14);
  a26=sin(a26);
  a25=(a25*a26);
  a9=(a9+a25);
  a25=sin(a7);
  a28=(a28*a25);
  a9=(a9-a28);
  a9=(a9/a30);
  a9=(a9/a30);
  a32=(a32+a32);
  a30=cos(a11);
  a32=(a32*a30);
  a31=(a31*a32);
  a9=(a9*a31);
  a27=(a27-a9);
  if (res[0]!=0) res[0][5]=a27;
  a45=(a43*a45);
  a38=(a36*a38);
  a42=(a40*a42);
  a38=(a38-a42);
  a45=(a45-a38);
  a49=(a47*a49);
  a45=(a45+a49);
  a52=(a50*a52);
  a45=(a45-a52);
  a55=(a10*a55);
  a55=(a53*a55);
  a45=(a45+a55);
  a59=(a57*a59);
  a45=(a45+a59);
  a60=(a1*a60);
  a45=(a45+a60);
  a60=arg[1]? arg[1][5] : 0;
  a59=arg[3]? arg[3][6] : 0;
  a55=casadi_sq(a4);
  a52=casadi_sq(a5);
  a55=(a55*a52);
  a52=casadi_sq(a6);
  a55=(a55*a52);
  a52=sin(a11);
  a49=(a52+a52);
  a38=cos(a11);
  a49=(a49*a38);
  a49=(a55*a49);
  a49=(a59*a49);
  a49=(a60*a49);
  a45=(a45-a49);
  a63=(a61*a63);
  a45=(a45-a63);
  a66=(a64*a66);
  a45=(a45-a66);
  a69=(a67*a69);
  a45=(a45+a69);
  a10=(a10*a72);
  a10=(a70*a10);
  a45=(a45-a10);
  a76=(a74*a76);
  a45=(a45-a76);
  a78=(a20*a78);
  a45=(a45-a78);
  a45=(a45/a79);
  a78=cos(a7);
  a34=(a34*a78);
  a41=cos(a41);
  a40=(a40*a41);
  a37=sin(a37);
  a36=(a36*a37);
  a40=(a40+a36);
  a34=(a34-a40);
  a40=cos(a7);
  a39=(a39*a40);
  a34=(a34+a39);
  a39=sin(a7);
  a8=(a8*a39);
  a34=(a34+a8);
  a8=sin(a7);
  a35=(a35*a8);
  a34=(a34+a35);
  a44=cos(a44);
  a43=(a43*a44);
  a34=(a34-a43);
  a43=cos(a7);
  a46=(a46*a43);
  a34=(a34+a46);
  a48=cos(a48);
  a47=(a47*a48);
  a34=(a34+a47);
  a51=cos(a51);
  a50=(a50*a51);
  a34=(a34+a50);
  a54=cos(a54);
  a53=(a53*a54);
  a34=(a34-a53);
  a53=cos(a7);
  a56=(a56*a53);
  a34=(a34+a56);
  a58=cos(a58);
  a57=(a57*a58);
  a34=(a34+a57);
  a2=cos(a2);
  a1=(a1*a2);
  a34=(a34-a1);
  a1=(a29*a16);
  a2=casadi_sq(a4);
  a29=(a29*a2);
  a29=(a29*a6);
  a1=(a1+a29);
  a29=casadi_sq(a18);
  a29=(a16*a29);
  a29=(a29*a19);
  a1=(a1+a29);
  a5=casadi_sq(a5);
  a16=(a16*a5);
  a16=(a16*a6);
  a1=(a1+a16);
  a18=casadi_sq(a18);
  a4=casadi_sq(a4);
  a18=(a18*a4);
  a18=(a18*a19);
  a18=(a18*a6);
  a1=(a1+a18);
  a52=casadi_sq(a52);
  a55=(a55*a52);
  a1=(a1+a55);
  a59=(a59*a1);
  a60=(a59*a60);
  a34=(a34-a60);
  a62=sin(a62);
  a61=(a61*a62);
  a34=(a34-a61);
  a61=sin(a7);
  a15=(a15*a61);
  a34=(a34+a15);
  a65=sin(a65);
  a64=(a64*a65);
  a34=(a34+a64);
  a68=sin(a68);
  a67=(a67*a68);
  a34=(a34+a67);
  a71=sin(a71);
  a70=(a70*a71);
  a34=(a34-a70);
  a7=sin(a7);
  a73=(a73*a7);
  a34=(a34+a73);
  a75=sin(a75);
  a74=(a74*a75);
  a34=(a34+a74);
  a77=sin(a77);
  a20=(a20*a77);
  a34=(a34-a20);
  a34=(a34/a79);
  a34=(a34/a79);
  a81=(a81+a81);
  a11=cos(a11);
  a81=(a81*a11);
  a80=(a80*a81);
  a34=(a34*a80);
  a45=(a45-a34);
  if (res[0]!=0) res[0][6]=a45;
  if (res[0]!=0) res[0][7]=a0;
  a59=(a59/a79);
  a59=(-a59);
  if (res[0]!=0) res[0][8]=a59;
  return 0;
}

CASADI_SYMBOL_EXPORT int jacF(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int jacF_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int jacF_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void jacF_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int jacF_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void jacF_release(int mem) {
}

CASADI_SYMBOL_EXPORT void jacF_incref(void) {
}

CASADI_SYMBOL_EXPORT void jacF_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int jacF_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int jacF_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real jacF_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* jacF_name_in(casadi_int i) {
  switch (i) {
    case 0: return "t";
    case 1: return "x";
    case 2: return "z";
    case 3: return "p";
    case 4: return "u";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* jacF_name_out(casadi_int i) {
  switch (i) {
    case 0: return "jac_ode_x";
    case 1: return "jac_alg_x";
    case 2: return "jac_ode_z";
    case 3: return "jac_alg_z";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* jacF_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* jacF_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int jacF_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
