/*
dipc_mpc : A fast customized optimization solver.

Copyright (C) 2013-2023 EMBOTECH AG [info@embotech.com]. All rights reserved.


This software is intended for simulation and testing purposes only. 
Use of this software for any commercial purpose is prohibited.

This program is distributed in the hope that it will be useful.
EMBOTECH makes NO WARRANTIES with respect to the use of the software 
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
PARTICULAR PURPOSE. 

EMBOTECH shall not have any liability for any damage arising from the use
of the software.

This Agreement shall exclusively be governed by and interpreted in 
accordance with the laws of Switzerland, excluding its principles
of conflict of laws. The Courts of Zurich-City shall have exclusive 
jurisdiction in case of any dispute.

*/

/* Generated by FORCESPRO v6.3.0 on Monday, January 6, 2025 at 8:04:11 PM */
#ifndef dipc_mpc_H
#define dipc_mpc_H

#ifndef SOLVER_STDIO_H
#define SOLVER_STDIO_H
#include <stdio.h>
#endif
#ifndef SOLVER_STRING_H
#define SOLVER_STRING_H
#include <string.h>
#endif


#ifndef SOLVER_STANDARD_TYPES
#define SOLVER_STANDARD_TYPES

typedef signed char solver_int8_signed;
typedef unsigned char solver_int8_unsigned;
typedef char solver_int8_default;
typedef signed short int solver_int16_signed;
typedef unsigned short int solver_int16_unsigned;
typedef short int solver_int16_default;
typedef signed int solver_int32_signed;
typedef unsigned int solver_int32_unsigned;
typedef int solver_int32_default;
typedef signed long long int solver_int64_signed;
typedef unsigned long long int solver_int64_unsigned;
typedef long long int solver_int64_default;

#endif


/* DATA TYPE ------------------------------------------------------------*/
typedef double dipc_mpc_float;
typedef double dipc_mpc_ldl_s_float;
typedef double dipc_mpc_ldl_r_float;
typedef double dipc_mpc_callback_float;

typedef double dipc_mpcinterface_float;

/* SOLVER SETTINGS ------------------------------------------------------*/

/* MISRA-C compliance */
#ifndef MISRA_C_dipc_mpc
#define MISRA_C_dipc_mpc (0)
#endif

/* restrict code */
#ifndef RESTRICT_CODE_dipc_mpc
#define RESTRICT_CODE_dipc_mpc (0)
#endif

/* print level */
#ifndef SET_PRINTLEVEL_dipc_mpc
#define SET_PRINTLEVEL_dipc_mpc    (1)
#endif

/* timing */
#ifndef SET_TIMING_dipc_mpc
#define SET_TIMING_dipc_mpc    (1)
#endif

/* Numeric Warnings */
/* #define PRINTNUMERICALWARNINGS */

/* maximum number of iterations  */
#define SET_MAXIT_dipc_mpc			(200)	

/* scaling factor of line search (FTB rule) */
#define SET_FLS_SCALE_dipc_mpc		(dipc_mpc_float)(0.99)      

/* maximum number of supported elements in the filter */
#define MAX_FILTER_SIZE_dipc_mpc	(200) 

/* whether callback return values should be checked */
#define EXTFUNC_RETURN_dipc_mpc (0)

/* SOLVER RETURN CODES----------------------------------------------------------*/
/* solver has converged within desired accuracy */
#define OPTIMAL_dipc_mpc      (1)

/* maximum number of iterations has been reached */
#define MAXITREACHED_dipc_mpc (0)

/* solver has stopped due to a timeout */
#define TIMEOUT_dipc_mpc   (2)

/* solver stopped externally */
#define EXIT_EXTERNAL_dipc_mpc (3)

/* wrong number of inequalities error */
#define INVALID_NUM_INEQ_ERROR_dipc_mpc  (-4)

/* factorization error */
#define FACTORIZATION_ERROR_dipc_mpc   (-5)

/* NaN encountered in function evaluations */
#define BADFUNCEVAL_dipc_mpc  (-6)

/* invalid value (<= -100) returned by external function */
#define INVALIDFUNCEXIT_dipc_mpc (-200)

/* bad value returned by external function */
#define BADFUNCEXIT_dipc_mpc(status) (status > -100? status - 200 : INVALIDFUNCEXIT_dipc_mpc)

/* no progress in method possible */
#define NOPROGRESS_dipc_mpc   (-7)

/* regularization error */
#define REGULARIZATION_ERROR_dipc_mpc   (-9)

/* invalid values in parameters */
#define PARAM_VALUE_ERROR_dipc_mpc   (-11)

/* too small timeout given */
#define INVALID_TIMEOUT_dipc_mpc   (-12)

/* thread error */
#define THREAD_FAILURE_dipc_mpc  (-98)

/* locking mechanism error */
#define LOCK_FAILURE_dipc_mpc  (-99)

/* licensing error - solver not valid on this machine */
#define LICENSE_ERROR_dipc_mpc  (-100)

/* Insufficient number of internal memory instances.
 * Increase codeoptions.max_num_mem. */
#define MEMORY_INVALID_dipc_mpc (-101)
/* Number of threads larger than specified.
 * Increase codeoptions.nlp.max_num_threads. */
#define NUMTHREADS_INVALID_dipc_mpc (-102)


/* INTEGRATORS RETURN CODE ------------*/
/* Integrator ran successfully */
#define INTEGRATOR_SUCCESS (11)
/* Number of steps set by user exceeds maximum number of steps allowed */
#define INTEGRATOR_MAXSTEPS_EXCEEDED (12)


/* MEMORY STRUCT --------------------------------------------------------*/
typedef struct dipc_mpc_mem dipc_mpc_mem;
#ifdef __cplusplus
extern "C" {
#endif
/* MEMORY STRUCT --------------------------------------------------------*/
extern dipc_mpc_mem * dipc_mpc_external_mem(void * mem_ptr, solver_int32_unsigned i_mem, size_t mem_size);
extern size_t dipc_mpc_get_mem_size( void );
extern size_t dipc_mpc_get_const_size( void );
#ifdef __cplusplus
}
#endif

/* PARAMETERS -----------------------------------------------------------*/
/* fill this with data before calling the solver! */
typedef struct
{
    /* vector of size 140 */
    dipc_mpc_float x0[140];

    /* vector of size 6 */
    dipc_mpc_float xinit[6];

    /* vector of size 140 */
    dipc_mpc_float all_parameters[140];


} dipc_mpc_params;


/* OUTPUTS --------------------------------------------------------------*/
/* the desired variables are put here by the solver */
typedef struct
{
    /* column vector of length 7 */
    dipc_mpc_float x01[7];

    /* column vector of length 7 */
    dipc_mpc_float x02[7];

    /* column vector of length 7 */
    dipc_mpc_float x03[7];

    /* column vector of length 7 */
    dipc_mpc_float x04[7];

    /* column vector of length 7 */
    dipc_mpc_float x05[7];

    /* column vector of length 7 */
    dipc_mpc_float x06[7];

    /* column vector of length 7 */
    dipc_mpc_float x07[7];

    /* column vector of length 7 */
    dipc_mpc_float x08[7];

    /* column vector of length 7 */
    dipc_mpc_float x09[7];

    /* column vector of length 7 */
    dipc_mpc_float x10[7];

    /* column vector of length 7 */
    dipc_mpc_float x11[7];

    /* column vector of length 7 */
    dipc_mpc_float x12[7];

    /* column vector of length 7 */
    dipc_mpc_float x13[7];

    /* column vector of length 7 */
    dipc_mpc_float x14[7];

    /* column vector of length 7 */
    dipc_mpc_float x15[7];

    /* column vector of length 7 */
    dipc_mpc_float x16[7];

    /* column vector of length 7 */
    dipc_mpc_float x17[7];

    /* column vector of length 7 */
    dipc_mpc_float x18[7];

    /* column vector of length 7 */
    dipc_mpc_float x19[7];

    /* column vector of length 7 */
    dipc_mpc_float x20[7];


} dipc_mpc_output;


/* SOLVER INFO ----------------------------------------------------------*/
/* diagnostic data from last interior point step */
typedef struct
{
    /* scalar: iteration number */
    solver_int32_default it;

    /* scalar: number of iterations needed to optimality (branch-and-bound) */
    solver_int32_default it2opt;

    /* scalar: inf-norm of equality constraint residuals */
    dipc_mpc_float res_eq;

    /* scalar: inf-norm of inequality constraint residuals */
    dipc_mpc_float res_ineq;

    /* scalar: norm of stationarity condition */
    dipc_mpc_float rsnorm;

    /* scalar: max of all complementarity violations */
    dipc_mpc_float rcompnorm;

    /* scalar: primal objective */
    dipc_mpc_float pobj;

    /* scalar: dual objective */
    dipc_mpc_float dobj;

    /* scalar: duality gap := pobj - dobj */
    dipc_mpc_float dgap;

    /* scalar: relative duality gap := |dgap / pobj | */
    dipc_mpc_float rdgap;

    /* scalar: duality measure */
    dipc_mpc_float mu;

    /* scalar: duality measure (after affine step) */
    dipc_mpc_float mu_aff;

    /* scalar: centering parameter */
    dipc_mpc_float sigma;

    /* scalar: number of backtracking line search steps (affine direction) */
    solver_int32_default lsit_aff;

    /* scalar: number of backtracking line search steps (combined direction) */
    solver_int32_default lsit_cc;

    /* scalar: step size (affine direction) */
    dipc_mpc_float step_aff;

    /* scalar: step size (combined direction) */
    dipc_mpc_float step_cc;

    /* scalar: total solve time */
    dipc_mpc_float solvetime;

    /* scalar: time spent in function evaluations */
    dipc_mpc_float fevalstime;

    /* column vector of length 8: solver ID of FORCESPRO solver */
    solver_int32_default solver_id[8];




} dipc_mpc_info;







/* SOLVER FUNCTION DEFINITION -------------------------------------------*/
/* Time of Solver Generation: (UTC) Monday, January 6, 2025 8:04:13 PM */
/* User License expires on: (UTC) Sunday, February 2, 2025 10:00:00 PM (approx.) (at the time of code generation) */
/* Solver Static License expires on: (UTC) Sunday, February 2, 2025 10:00:00 PM (approx.) */
/* Solver Id: a2c9aede-dc72-45a7-a0c8-f95eeef53d45 */
/* Host Compiler Version: d76500f0 */
/* Target Compiler Version: unused */
/* examine exitflag before using the result! */
#ifdef __cplusplus
extern "C" {
#endif		

typedef solver_int32_default (*dipc_mpc_extfunc)(dipc_mpc_float* x, dipc_mpc_float* y, dipc_mpc_float* lambda, dipc_mpc_float* params, dipc_mpc_float* pobj, dipc_mpc_float* g, dipc_mpc_float* c, dipc_mpc_float* Jeq, dipc_mpc_float* h, dipc_mpc_float* Jineq, dipc_mpc_float* H, solver_int32_default stage, solver_int32_default iterations, solver_int32_default threadID);

extern solver_int32_default dipc_mpc_solve(dipc_mpc_params *params, dipc_mpc_output *output, dipc_mpc_info *info, dipc_mpc_mem *mem, FILE *fs, dipc_mpc_extfunc evalextfunctions_dipc_mpc);











#ifdef __cplusplus
}
#endif

#endif
